name: Daily Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, freebsd]
        goarch: [386, amd64, arm, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'MartialBE/one-api'
        path: 'one-api'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15' # 根据项目需求设置Go版本

    - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
      run: |
        cd one-api
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release notes for ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: one-api/one-api-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: one-api-${{ github.ref }}-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_content_type: application/octet-stream
