name: Daily Build and Release

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜（UTC时间）执行
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, freebsd]
        goarch: [386, amd64, arm, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'MartialBE/one-api'
        fetch-depth: 0 # 获取所有tags

    - name: Get latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Latest tag is $latest_tag"
        echo "::set-output name=tag::$latest_tag"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15' # 根据项目需求设置Go版本

    - name: Build with Make for ${{ matrix.goos }}-${{ matrix.goarch }}
      run: |
        make build-${{ matrix.goos }}-${{ matrix.goarch }}
        # 假设 make 命令生成的文件名为 one-api-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.get_latest_tag.outputs.tag }}
        release_name: Release ${{ steps.get_latest_tag.outputs.tag }}
        body: |
          Release notes for ${{ steps.get_latest_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./one-api-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: one-api-${{ steps.get_latest_tag.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_content_type: application/octet-stream
